Repository LikeMindsCommunity/likeminds-feed-flutter, pull requests merged in 2024-09, with the labels that each got.

#104 [LM-2722] fixed cusomisation testing bugs
  packages/integration/lib/src/bloc/personalised_feed/handler/get_feed_handler.dart
  packages/integration/lib/src/utils/builder/widget_utility.dart
  packages/integration/lib/src/views/feed/personalised_feed/personalised_feed_screen.dart
  packages/integration/lib/src/views/post/bottom_textfield.dart
  packages/integration/lib/src/views/post/bottom_textfield_banner.dart
  packages/integration/lib/src/views/post/post_detail_screen.dart
  packages/ui/lib/packages/expandable_text/expandable_text.dart
  packages/ui/lib/src/widgets/comment/comment_tile.dart
  packages/ui/lib/src/widgets/post/post_header.dart
Labels: bug

#105 [LM-12739] Add support to flutter version 3.24.0
  packages/integration/lib/src/views/feed/personalised_feed/personalised_feed_screen.dart
  packages/integration/lib/src/views/media/media_preview_screen.dart
  packages/integration/pubspec.yaml
  packages/ui/lib/src/widgets/media/carousel.dart
  packages/ui/pubspec.yaml
Labels: enhancement

#106 Version/v1.9.0
  example/pubspec.yaml
  packages/integration/CHANGELOG.md
  packages/integration/pubspec.yaml
  packages/ui/CHANGELOG.md
  packages/ui/pubspec.yaml
  pubspec.yaml
Labels: enhancement

#107 Release/v1.9.0
  example/lib/cred_screen.dart
  example/lib/themes/qna/builder/feed/lm_qna_feed.dart
  example/lib/themes/qna/builder/topic/topic_detail_screen.dart
  example/pubspec.yaml
  example/pubspec_overrides.yaml
  packages/integration/CHANGELOG.md
  packages/integration/lib/likeminds_feed_core.dart
  packages/integration/lib/src/bloc/bloc.dart
  packages/integration/lib/src/bloc/comment/comment_bloc.dart
  packages/integration/lib/src/bloc/comment/comment_event.dart
  packages/integration/lib/src/bloc/comment/handler/submit_comment_button_handler.dart
  packages/integration/lib/src/bloc/personalised_feed/handler/get_feed_handler.dart
  packages/integration/lib/src/bloc/personalised_feed/handler/refresh_feed_handler.dart
  packages/integration/lib/src/bloc/personalised_feed/handler/seen_post_handler.dart
  packages/integration/lib/src/bloc/personalised_feed/personalised_feed_bloc.dart
  packages/integration/lib/src/bloc/personalised_feed/personalised_feed_event.dart
  packages/integration/lib/src/bloc/personalised_feed/personalised_feed_state.dart
  packages/integration/lib/src/bloc/universal_feed/handler/refresh_feed_handler.dart
  packages/integration/lib/src/bloc/universal_feed/universal_feed_bloc.dart
  packages/integration/lib/src/bloc/universal_feed/universal_feed_event.dart
  packages/integration/lib/src/bloc/universal_feed/universal_feed_state.dart
  packages/integration/lib/src/builder/feed_builder_delegate.dart
  packages/integration/lib/src/utils/builder/widget_utility.dart
  packages/integration/lib/src/utils/typedefs.dart
  packages/integration/lib/src/views/feed/feed_screen.dart
  packages/integration/lib/src/views/feed/feed_screen_builder_delegate.dart
  packages/integration/lib/src/views/feed/feed_screen_configuration.dart
  packages/integration/lib/src/views/feed/personalised_feed/personalised_feed_screen.dart
  packages/integration/lib/src/views/feed/universal_feed/universal_feed_screen.dart
  packages/integration/lib/src/views/feedroom/feedroom_screen_configuration.dart
  packages/integration/lib/src/views/media/media_preview_screen.dart
  packages/integration/lib/src/views/post/bottom_textfield.dart
  packages/integration/lib/src/views/post/bottom_textfield_banner.dart
  packages/integration/lib/src/views/post/post_detail_screen.dart
  packages/integration/lib/src/views/views.dart
  packages/integration/lib/src/widgets/lists/feed/feed_list.dart
  packages/integration/pubspec.yaml
  packages/ui/CHANGELOG.md
  packages/ui/lib/packages/expandable_text/expandable_text.dart
  packages/ui/lib/src/utils/enums.dart
  packages/ui/lib/src/utils/theme/theme.dart
  packages/ui/lib/src/utils/typedefs.dart
  packages/ui/lib/src/widgets/comment/comment_tile.dart
  packages/ui/lib/src/widgets/common/profile/profile_picture.dart
  packages/ui/lib/src/widgets/media/carousel.dart
  packages/ui/lib/src/widgets/post/post.dart
  packages/ui/lib/src/widgets/post/post_header.dart
  packages/ui/pubspec.yaml
  pubspec.yaml
Labels: enhancement

#108 [WIP] Added customisations in LMFeedComposeScreen's AppBar builder
  packages/integration/lib/src/utils/builder/widget_utility.dart
  packages/integration/lib/src/views/compose/compose_screen.dart
Labels: enhancement

#110 [LM-12751] Removed flex from compose appbar
  packages/ui/lib/src/widgets/common/extras/appbar.dart
Labels: enhancement

#113 [LM-12783] Fixed feed issues
  packages/integration/lib/src/utils/tagging/tagging_textfield_ta.dart
  packages/integration/lib/src/utils/typedefs.dart
  packages/integration/lib/src/views/compose/compose_screen.dart
  packages/integration/lib/src/views/post/bottom_textfield.dart
  packages/integration/lib/src/views/post/edit_post_screen.dart
  packages/integration/lib/src/views/post/post_detail_screen.dart
  packages/integration/lib/src/widgets/post/comment/comment_list_widget.dart
  packages/integration/lib/src/widgets/post/comment/comment_reply_widget.dart
  packages/ui/lib/src/utils/typedefs.dart
  packages/ui/lib/src/widgets/comment/comment_tile.dart
  packages/ui/lib/src/widgets/common/extras/loader.dart
Labels: bug

#114 [LM-12798] Fixed bloc close issue
  packages/integration/lib/src/bloc/analytics/analytics_bloc.dart
  packages/integration/lib/src/bloc/compose/compose_bloc.dart
  packages/integration/lib/src/bloc/feedroom/feedroom_bloc.dart
  packages/integration/lib/src/bloc/pending_post/pending_bloc.dart
  packages/integration/lib/src/bloc/personalised_feed/personalised_feed_bloc.dart
  packages/integration/lib/src/bloc/post/post_bloc.dart
  packages/integration/lib/src/bloc/profile/profile_bloc.dart
  packages/integration/lib/src/bloc/routing/routing_bloc.dart
  packages/integration/lib/src/bloc/saved_post/saved_post_bloc.dart
  packages/integration/lib/src/bloc/universal_feed/universal_feed_bloc.dart
  packages/integration/lib/src/bloc/user_meta/user_meta_bloc.dart
  packages/integration/lib/src/views/feedroom/feedroom_screen.dart
Labels: bug

#115 Version/v1.9.2
  example/pubspec.yaml
  packages/integration/CHANGELOG.md
  packages/integration/pubspec.yaml
  packages/ui/CHANGELOG.md
  packages/ui/pubspec.yaml
  pubspec.yaml
Labels: documentation

#116 Release/v1.9.2
  example/pubspec.yaml
  packages/integration/CHANGELOG.md
  packages/integration/lib/src/bloc/analytics/analytics_bloc.dart
  packages/integration/lib/src/bloc/compose/compose_bloc.dart
  packages/integration/lib/src/bloc/feedroom/feedroom_bloc.dart
  packages/integration/lib/src/bloc/pending_post/pending_bloc.dart
  packages/integration/lib/src/bloc/personalised_feed/personalised_feed_bloc.dart
  packages/integration/lib/src/bloc/post/post_bloc.dart
  packages/integration/lib/src/bloc/profile/profile_bloc.dart
  packages/integration/lib/src/bloc/routing/routing_bloc.dart
  packages/integration/lib/src/bloc/saved_post/saved_post_bloc.dart
  packages/integration/lib/src/bloc/universal_feed/universal_feed_bloc.dart
  packages/integration/lib/src/bloc/user_meta/user_meta_bloc.dart
  packages/integration/lib/src/utils/tagging/tagging_textfield_ta.dart
  packages/integration/lib/src/utils/typedefs.dart
  packages/integration/lib/src/views/compose/compose_screen.dart
  packages/integration/lib/src/views/feedroom/feedroom_screen.dart
  packages/integration/lib/src/views/post/bottom_textfield.dart
  packages/integration/lib/src/views/post/edit_post_screen.dart
  packages/integration/lib/src/views/post/post_detail_screen.dart
  packages/integration/lib/src/widgets/post/comment/comment_list_widget.dart
  packages/integration/lib/src/widgets/post/comment/comment_reply_widget.dart
  packages/integration/pubspec.yaml
  packages/ui/CHANGELOG.md
  packages/ui/lib/src/utils/typedefs.dart
  packages/ui/lib/src/widgets/comment/comment_tile.dart
  packages/ui/lib/src/widgets/common/extras/loader.dart
  packages/ui/pubspec.yaml
  pubspec.yaml
Labels: bug
